language: node_js
cache:
  directories:
    - node_modules
node_js:
- '6.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_script: cat ./test/coverage-karma/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
- npm start -- build
deploy:
  provider: firebase
  skip_cleanup: true
  token: "$FIREBASE_TOKEN"
  on:
    branch:
    - master
