language: node_js
node_js:
- "6.1"
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_script: "cat ./test/coverage-karma/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  bucket: bizhub.io
  region: $AWS_DEFAULT_REGION
  local_dir: dist
  on:
    branch: master
