language: node_js
node_js:
- '6.1'
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm test
after_script: cat ./test/coverage-karma/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  buildpack: nodejs
  api_key: "$HEROKU_API_KEY"
  app: bizhub
  on:
    branch:
    - master
